---
title: |
  | \vspace{2cm} \textbf{``Shorties'' in Germany} \vspace{1cm}
author: | 
  | \textsc{Thomas Ludwig}
  | Thomas.Ludwig95@gmail.com
date: |
  | `r format(Sys.time(), '%d. %B %Y')` \vspace{1cm}
output: 
  pdf_document:
    number_sections: true
    fig_caption: true
header-includes:
- \usepackage{graphicx}
- \usepackage[english]{babel}
- \usepackage{xcolor}
- \usepackage{booktabs}
- \usepackage[]{microtype}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[hang, small, bf, margin=20pt, tableposition=top]{caption}
- \setlength{\abovecaptionskip}{0pt}
fontsize: 12pt
spacing: double
geometry: margin=1in
documentclass: "article"
abstract: |
  This document presents data of short positions on stocks traded in Germany. The
  data is taken from German Bundesanzeiger [[Link](https://www.bundesanzeiger.de/ebanzwww/wexsservlet?page.navid=to_nlp_start)].
  In Germany, investment firms have to report their net position in a short position
  if the total net position on a firm is $>$ 0.5%. The data represents the current
  short positions of a firm, no closed positions are considered. The website is updated on
  a daily basis.
---

\newpage

\tableofcontents

\listoftables

\newpage

```{r setup, include=FALSE}

# basic report setup and packages for analysis

# define global knitr options
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos = 'H') # needed to hold plot position with captions
knitr::opts_chunk$set(fig.width=12, fig.height=8) # define global plot dimensions

# used packages for analysis
library(rvest)
library(dplyr)
library(kableExtra)

```

```{r data_load, include=FALSE}

# data import and cleansing

# define starting page
url_start <- "https://www.bundesanzeiger.de/ebanzwww/wexsservlet?page.navid=to_nlp_start"

# define web scraping function
getPostContent <- function(url){
  cont <- read_html(url) %>% # read html from given url
    html_table(fill = TRUE) # extract html table directly from website
  cont[[1]] <- NULL # delete first table which is not clean
  
  # add some random sleep time to web scraper to avoid server overload
  Sys.sleep(sample(seq(1, 3, by=0.001), 1))
  
  return(cont)
}

# define function to go back in website
getNextUrl <- function(url) {
  scraped_url <- read_html(url) %>% 
    html_node(".next_page a") %>%
    html_attr("href")
  
  paste0("https://www.bundesanzeiger.de", scraped_url)
}

# combine functions to scrape data from each page in one call
scrapeBackApply <- function(url, n) {
  # url: starting url
  # n: how many subpages do we want to go back?
  sapply(1:n, function(x) {
    r <- getPostContent(url)
    # Overwrite global 'url'
    url <<- getNextUrl(url)
    r
  })
}

# use function on website
data_scraped <- scrapeBackApply(url = url_start, 15)

# merge data to one data frame
all_test <- do.call(rbind.data.frame, data_scraped)

# clean data for data manipulation
all_test$Emittent <- gsub("Historie", "", all_test$Emittent)
all_test$Emittent <- gsub("[[:punct:]]", "", all_test$Emittent)
all_test$Datum <- as.Date(all_test$Datum, "%Y-%m-%d")
all_test$Position <- as.numeric(gsub("[\\%,]", "", gsub(",", ".", all_test$Position)))/100

################################################################################

# name cleaning (we have unambiguous names which we have to consolidate)

names <- all_test %>%
  filter(Datum > "2020-01-01") %>%
  select(ISIN, Emittent) %>%
  distinct()

# next code is used to manually correct the names in the data

# count <- names %>%
#   group_by(ISIN) %>%
#   summarise(count = n()) %>%
#   filter(count >1)
# 
# names_cleaning <- all_test %>%
#   filter(Datum > "2020-01-01") %>%
#   select(ISIN, Emittent) %>%
#   distinct() %>%
#   filter(., ISIN %in% count$ISIN) %>%
#   arrange(ISIN)

# this data frame was set up by hand for the 2020 data!
names_correct <- data.frame(ISIN = c("DE0006452907", "DE0007500001",
                                     "DE000A0TGJ55", "LU1296758029",
                                     "NL0012044747", "US3994732069"),
                            Emittent = c("Nemetschek SE", "ThyssenKrupp Aufzugswerke GmbH",
                                         "VARTA Microbattery GmbH", "Corestate Capital Holding",
                                         "SHOP APOTHEKE EUROPE NV", "GROUPON INC"))

count_clean <- names %>%
  group_by(ISIN) %>%
  summarise(count = n()) %>%
  filter(count == 1)

names_clean <- all_test %>%
  filter(Datum > "2020-01-01") %>%
  select(ISIN, Emittent) %>%
  distinct() %>%
  filter(., ISIN %in% count_clean$ISIN)
  
names_clean <- rbind(names_clean, names_correct)

```

# Top Targets 2020 (Net Short Position $>$ 1%)

```{r, include=FALSE}

# top open short positions in 2020
top_short <- all_test %>%
  filter(Datum > "2020-01-01") %>% # consider only data from 2020
  group_by(ISIN) %>% 
  summarise(Short_Holding = sum(Position)) %>%
  mutate(Short_Holding = Short_Holding * 100) %>% # value in %
  filter(Short_Holding > 1) %>% # we only show positions with net position > 1 %
  arrange(desc(Short_Holding)) %>% # order by size of net position
  left_join(., names_clean) %>% # join with corrected name data
  relocate(Emittent, .before = Short_Holding) # change order of columns

```

```{r, echo=FALSE}

kable(top_short, "latex", booktabs = TRUE, caption = "Top Targets (Net Position in Percent)", linesep = "", longtable = TRUE) %>%
  kable_styling(position = "center", latex_options = c("hold_position", "repeat_header"))

```


\newpage

# Top Targets 2020 (Active Hedge Fund Positions)

```{r, include=FALSE}

# top open short positions by number of hedge fund position in 2020
top_short_count <- all_test %>%
  filter(Datum > "2020-01-01") %>%
  group_by(ISIN) %>%
  summarise(Short_Count = n()) %>%
  filter(Short_Count > 1) %>%
  arrange(desc(Short_Count)) %>%
  left_join(., names_clean) %>% # join with corrected name data
  relocate(Emittent, .before = Short_Count) # change order of columns

```


```{r, echo=FALSE}

kable(top_short_count, "latex", booktabs = T, caption = "Top Targets (Different Hedge Fund Positions Count)", 
      linesep = "") %>%
  kable_styling(position = "center", latex_options = "hold_position")

```

\newpage

# Most Active Hedge Funds

## Most Active Hedge Funds (2020 Active Positions Count)

```{r, include=FALSE}

# most active hedge funds by number of positions in 2020
hedge_fund_count <- all_test %>%
  filter(Datum > "2020-01-01") %>%
  group_by(Positionsinhaber) %>%
  summarise(position_count = n()) %>%
  arrange(desc(position_count))

```

```{r, echo=FALSE}

kable(hedge_fund_count, "latex", booktabs = T, caption = "Most active Hedge Funds (2020)", 
      linesep = "", longtable = TRUE) %>%
  kable_styling(position = "center", latex_options = c("hold_position", "repeat_header"))

```


## Most Active Hedge Funds (Full Sample Active Positions Count)

```{r, include=FALSE}

# most active hedge funds by number of positions for total sample
hedge_fund_count_all <- all_test %>%
  group_by(Positionsinhaber) %>%
  summarise(position_count = n()) %>%
  arrange(desc(position_count))

```

```{r, echo=FALSE}

kable(hedge_fund_count_all, "latex", booktabs = T, caption = "Most active Hedge Funds (Full Sample)", linesep = "", longtable = TRUE) %>%
  kable_styling(position = "center", latex_options = c("hold_position", "repeat_header"))

```
